### ISSUE TITLE
TypeError with string formatting

### ISSUE THREAD

**Issue by wholtz** [shahzebsiddiqui/jobstats#6]
On cori @ NERSC:

```
$ module load python/3.9-anaconda-2021.11
$ jobstats
Traceback (most recent call last):
  File "/usr/common/software/bin/jobstats", line 253, in <module>
    main()
  File "/usr/common/software/bin/jobstats", line 135, in main
    parser.add_argument("-v", "--version", help="Print version", action="version", version="%(prog)s version %s" % JOBSTATS_VERSION )
TypeError: format requires a mapping
$ 
```

**Comment by shahzebsiddiqui** [comment]
Hi @wholtz,

Thanks for bring this up i was able to reproduce your error and made this fix in https://github.com/shahzebsiddiqui/jobstats/pull/7. 

I did some testing to ensure this works 

python 3.7

```
└─(08:08:14 on fix_typerror)──> python --version                                            ──(Wed,Feb23)─┘
Python 3.7.3
└─(08:06:33 on fix_typerror)──> which python                                                ──(Wed,Feb23)─┘
/usr/common/software/python/3.7-anaconda-2019.07/bin/python
└─(08:06:48 on fix_typerror)──> ./jobstats --version                                        ──(Wed,Feb23)─┘
jobstats version 0.2
```

With python 3.8

```
└─(08:08:56 on fix_typerror)──> python --version                                            ──(Wed,Feb23)─┘
Python 3.8.5
┌─(~/gitrepos/jobstats)─────────────────────────────────────────────────────────(siddiq90@cori04:pts/196)─┐
└─(08:09:01 on fix_typerror)──> ./jobstats --version                                        ──(Wed,Feb23)─┘
jobstats version 0.2
```

with python 3.9

```
└─(08:09:52 on fix_typerror)──> python --version                                            ──(Wed,Feb23)─┘
Python 3.9.7
┌─(~/gitrepos/jobstats)─────────────────────────────────────────────────────────(siddiq90@cori04:pts/196)─┐
└─(08:09:55 on fix_typerror)──> ./jobstats --version                                        ──(Wed,Feb23)─┘
jobstats version 0.2
```

with python 2.x should raise an exception.

```
└─(08:10:17 on fix_typerror)──> python --version                                            ──(Wed,Feb23)─┘
Python 2.7.18
┌─(~/gitrepos/jobstats)─────────────────────────────────────────────────────────(siddiq90@cori04:pts/196)─┐
└─(08:10:22 on fix_typerror)──> ./jobstats --version                                        ──(Wed,Feb23)─┘
Traceback (most recent call last):
  File "./jobstats", line 252, in <module>
    check_python_version()
  File "./jobstats", line 248, in check_python_version
    raise Exception("%s only compatible with Python 3.X version" % sys.argv[0])
Exception: ./jobstats only compatible with Python 3.X version
```

**Comment by shahzebsiddiqui** [comment]
Jobstats is now available on Perlmutter as well. If you have any questions or suggestions to improve jobstats  please feel free to raise an issue.
